### PR TITLE
Utilize generator comprehensions.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by bhelx** [comment]
Hey @frewsxcv 

Sorry I missed this. Can you comment on what this does and why it's needed?

**Comment by frewsxcv** [comment]
Previously, it was a [list comprehension](https://docs.python.org/2/tutorial/datastructures.html#list-comprehensions), now it's a [generator expression](https://www.python.org/dev/peps/pep-0289/). Generators are more memory efficient as it only allocates memory per-element in the iterator, as opposed to a list comprehension which allocates the entire list before iterating.

**Comment by bhelx** [comment]
@frewsxcv Thanks, I'll review this first thing in the morning. It should be an easy merge!

**Comment by bhelx** [comment]
:+1:

**Pull request merged**
