### PR TITLE
Correct __str__ behaviour on Python3

### PR DESCRIPTION
**Pull request by tbartelmess**
On Python 3, calling `str(self)` in def `__str__(self)` causes an infinite loop. I think it's fine to just call out to __unicode__ and return that. Python 2.x versions that still use __str__ are really old right now and not supported by this package anyway.

### CODE REVIEW

**Comment by bhelx** [comment]
Thank you @tbartelmess. We haven't been doing the best job of keeping up with python 3 support. Will take a look at this to go into the next release.

**Comment by bhelx** [comment]
@tbartelmess can you remove the stray .swp files?

**Comment by tbartelmess** [comment]
Oooops, yes sure.

**Comment by tbartelmess** [comment]
@bhelx rebased

**Comment by bhelx** [comment]
@tbartelmess thanks

**Comment by bhelx** [comment]
:+1:

**Pull request merged**
