### PR TITLE
Support for plans with fixed number of billing cycles

### PR DESCRIPTION
**Pull request by mgall**
Added support for the creation of plans with a fixed number of billing cycles.

### CODE REVIEW

**Comment by cbarton** [comment]
Thanks for the contribution! Can you add a CHANGELOG entry under `unreleased` please :)

**Comment by cbarton** [comment]
This needs to be rebased with master

**Comment by bhelx** [comment]
@mgall any update on rebase?

**Comment by bhelx** [comment]
Addressed here: https://github.com/recurly/recurly-client-ruby/pull/207

**Comment by bhelx** [comment]
Addressed here: https://github.com/recurly/recurly-client-python/pull/125

**Pull request closed without merging**
